### ISSUE TITLE
Data for pre-training

### ISSUE THREAD

**Issue by Elfenreigen** [Event-AHU/Medical_Image_Analysis#2]
I wonder about the composition of the 1M high-resolution pre-training dataset. Does your institution collect this huge dataset? Thanks.

**Comment by wangxiao5791509** [comment]
@Elfenreigen   Hi, thanks for your attention on this work. The dataset was obtained from a common database shared by multiple hospitals, but due to data privacy concerns, details cannot be disclosed.

**Comment by Elfenreigen** [comment]
Thanks.
