### ISSUE TITLE
How to access the annotation of Chexpert plus

### ISSUE THREAD

**Issue by ClementFYJ** [Event-AHU/Medical_Image_Analysis#5]
Hi, 

May I ask where could I find the annotation of chexpert plus. Is it in  a 14-labels form or in natural language. I tried to use your pre-annotated version yet I found that there are some missing samples. Could you please indicate how to get the original annotation files. Thanks

**Comment by QwYko-AHU** [comment]
Hi，
You can find the original CSV format configuration files for the CheXpert Plus dataset on the official CheXpert Plus website. They are in natural language format, and you can find them [there](https://stanfordaimi.azurewebsites.net/datasets/5158c524-d3ab-4e02-96e9-6ee9efc110a1).
