### ISSUE TITLE
Why does R2GenCSR use truncated ground truth in calculating metrics?

### ISSUE THREAD

**Issue by xzp9999** [Event-AHU/Medical_Image_Analysis#6]
When calculating the metrics, it appears that the references are based on truncated results. This may lead to the loss of important information, as conventionally the full report content is used for such calculations. I would like to inquire about the rationale behind choosing to implement a truncation strategy in this context.
![image](https://github.com/user-attachments/assets/a57ccb78-da07-4da3-b25a-c931863ade08)
![image](https://github.com/user-attachments/assets/0a346170-c884-4238-bd3a-02a7d80da64e)

**Comment by wangxiao5791509** [comment]
@xzp9999  Hello, thank you for your attention to our work. We have actually noticed this issue as well. However, in order to be as consistent as possible with previous work such as r2gen, we have truncated the precision calculation to maintain a relatively fair comparison.

**Comment by wangxiao5791509** [comment]
@xzp9999  In our newly built benchmark for the CheXpert Plus dataset, we train and test the models using complete GT for evaluation. We believe it will be a better benchmark for the X-ray medical report generation. 

https://github.com/Event-AHU/Medical_Image_Analysis/tree/main/CXPMRG_Bench_MambaXray_VL

**Comment by xzp9999** [comment]
> @xzp9999 在我们为 CheXpert Plus 数据集新构建的基准中，我们使用完整的 GT 来训练和测试模型以进行评估。我们相信它将成为 X 射线医疗报告生成的更好基准。
> 
> https://github.com/Event-AHU/Medical_Image_Analysis/tree/main/CXPMRG_Bench_MambaXray_VL

Thanks for the reply, this is very meaningful work🌹
